baseURL: "https://www.chive-tamagoyaki.com/"
languageCode: "en-us"
title: "Chive Tamagoyaki"
theme: "charlolamode"

menu:
    main:
        - name: About
          url: /about/
          weight: 5
        - name: Roleplay
          url: /rp/
          weight: 10
        # - name: Contact
        #   url: /contact/
        #   weight: 30
        # - name: Articles
        #   url: /articles/
        #   weight: 20
        # - name: Projects
        #   url: /projects/
        #   weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Chive


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: \@chive-tamagoyaki
        description: |

          (She/Her)

          Hello, you can call me Chive.  I'm a completely average nerd who enjoys coding, 
          roleplaying, anime, and games.  I'm an expert in the isekai genre.  You can check
          out the content I produce, the characters I create, and what my thoughts are about
          various topics.  

        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Free Onlyfans
              url: https://www.youtube.com/watch?v=OyvNMuSEj24

        title2: TEST
        content2: TEST TEST
    mainSections:
      - articles

    socialIcons:
        - name: youtube
          url: "https://www.youtube.com/channel/UCKFn6EP6cUMIqHeMBbH_SWQ"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true